### ISSUE TITLE
Text is not rendered in IE11

### ISSUE THREAD

**Issue by tomrimk** [d3plus/d3plus-text#114]
### Expected Behavior

Text is rendered and visible.

### Current Behavior

Text is not rendered.
### Steps to Reproduce (for bugs)

The problem can be seen in the example page of [d3plus.org](https://d3plus.org/examples/d3plus-text/getting-started/)
### Your Environment

* Browser Name: Internet Explorer 11.0.96
* Operating System and Version: Windows 8.1

![text-wrapping-ie](https://user-images.githubusercontent.com/31211514/63347839-adb35a80-c360-11e9-85f9-268075755eea.PNG)

**Comment by davelandry** [comment]
thanks for reporting @tomrimk! should be fixed for you now.

**Comment by tomrimk** [comment]
Hi @davelandry, thank you for the quick response!

The problem for my project still persist with the new version, so will try to find a problem on my side.

**Comment by davelandry** [comment]
@tomrimk sounds good, if you get stuck don't hesitate to post some code and error messages
