### ISSUE TITLE
improve ellipsis logic

### ISSUE THREAD

**Issue by geohuz** [d3plus/d3plus-text#44]
Doesn't work for long text.

**Comment by geohuz** [comment]
```
   var data = [{text: 'Pellentesque habitant morbi tristiqu'}]
    new d3plus.TextBox()
      .data(data)
      .fontSize(17)
      .width(50)
      .render();
```

I got the d3plus-text.full.js:3174 Uncaught TypeError: Cannot read property 'replace' of undefined,
further testing shows that sometimes the text element doesn't render at all, sometimes throw errors. I tried adjusting fontsize, width, height, and overflow options. The behavior is unpredictable.

**Comment by davelandry** [comment]
Good find. I've pushed a fix.

The reason text sometimes does not render, as in your case, is because the first word of your sentence cannot fit given the specified fontSize and width.

**Comment by geohuz** [comment]
@davelandry , thanks for the fix! Now I can confirm the error is gone, but I still see it renders nothing, when it is supposed to render ellipsis, in case of there is no enough room for rendering text in a single line.

**Comment by davelandry** [comment]
You're right, it should render an ellipsis in this case. I'll push that fix as well.

**Comment by davelandry** [comment]
@geohuz just pushed some tweaks to the logic, what do you think?

**Comment by geohuz** [comment]
Yeah! it works now!

**Comment by geohuz** [comment]
I got another issue with the long text rendering, and suspected that's related to this ticket, the rendering text is: "建立客户信息反馈机制，跟踪解决过程，问题解决率达到80%以上", throwing the following error: 

`
d3plus-text.js:210 Uncaught TypeError: Cannot read property 'trimRight' of undefined
`

I'm using the version 0.9.8

**Comment by davelandry** [comment]
That string is rendering an ellipsis for me, and not throwing any errors. Can you please post your full TextBox config or a jsfiddle?

**Comment by vincerubinetti** [comment]
@davelandry This looks like a great fix, but it was done almost three years ago it seems like? It seems that this fix is implemented in `v0.9.6`, but the latest version on `npm` is only `v0.9.43`. Can we expect an updated push to `npm` soon, or should I go back to d3plus 1.0 for this to work (I assume this works in 1.0).

As is, this issue makes the plugin unusable for me.
